name: imputer-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - pandas
  - tqdm
  - jupyter
  - networkx
  - pip
  - pip:
    - pgmpy==1.0.0
    - scikit-learn