python src/ablationRunner.py --examples_per_cycle 50 --experiment var_grad_imputed_weights --loss_type cross_entropy --resample_validation --dataset hanna --runner haojun --use_embedding True --cold_start True --validation_set_size 50 --active_set_size 100 --epochs_per_cycle 10 --train_option dynamic_masking_new --gradient_top_only True --num_patterns_per_example 3 --visible_ratio 0.5 --features_per_example 5 --batch_size 16 --experiment_name var_grad_imputed_loss --log_level INFO --output_path src/results --wandb_project active-learning-hanna --wandb_entity stonehj-johns-hopkins-university --cycles 12 --use_wandb

python src/ablationRunner.py --examples_per_cycle 50 --experiment var_grad_imputed_loss --loss_type cross_entropy --resample_validation --dataset hanna --runner haojun --use_embedding True --cold_start True --validation_set_size 50 --active_set_size 100 --epochs_per_cycle 10 --train_option dynamic_masking_new --gradient_top_only True --num_patterns_per_example 3 --visible_ratio 0.5 --features_per_example 5 --batch_size 16 --experiment_name var_grad_imputed_gradient_weights --log_level INFO --output_path src/results --wandb_project active-learning-hanna --wandb_entity stonehj-johns-hopkins-university --cycles 12 --use_wandb

python src/ablationRunner.py --examples_per_cycle 50 --experiment var_grad_dynamic_masking --loss_type cross_entropy --resample_validation --dataset hanna --runner haojun --use_embedding True --cold_start True --validation_set_size 50 --active_set_size 100 --epochs_per_cycle 10 --train_option dynamic_masking_new --gradient_top_only True --num_patterns_per_example 3 --visible_ratio 0.5 --features_per_example 5 --batch_size 16 --experiment_name var_grad_original --log_level INFO --output_path src/results --wandb_project active-learning-hanna --wandb_entity stonehj-johns-hopkins-university --cycles 12 --use_wandb

python src/ablationRunner.py --examples_per_cycle 50 --experiment var_grad_weight_loss --loss_type cross_entropy --resample_validation --dataset hanna --runner haojun --use_embedding True --cold_start True --validation_set_size 50 --active_set_size 100 --epochs_per_cycle 10 --train_option dynamic_masking_new --gradient_top_only True --num_patterns_per_example 3 --visible_ratio 0.5 --features_per_example 5 --batch_size 16 --experiment_name var_grad_weight_loss --log_level INFO --output_path src/results --wandb_project active-learning-hanna --wandb_entity stonehj-johns-hopkins-university --cycles 12 --use_wandb


